function createaxes(X1, Y1, Z1, X2, Y2, Z2)
%CREATEAXES(X1, Y1, Z1, X2, Y2, Z2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Z2:  vector of z data

%  Auto-generated by MATLAB on 02-Mar-2019 11:33:09

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1,'DisplayName','Desired','LineWidth',2,'LineStyle','--');

% Create plot3
plot3(X2,Y2,Z2,'DisplayName','Executed','LineWidth',2);

% Create xlabel
xlabel('X Position [m]');

% Create zlabel
zlabel('Z Position [m]');

% Create title
title('3D Position');

% Create ylabel
ylabel('Y Position [m]');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.771917740251001 7.91349712246636]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.43168447678237 4.253730385935]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1.08388941765866 5.86444247251523]);
view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1]);
